/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as V1ModelsRouteImport } from './routes/v1/models'
import { Route as V1ChatCompletionsRouteImport } from './routes/v1/chat/completions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const V1ModelsRoute = V1ModelsRouteImport.update({
  id: '/v1/models',
  path: '/v1/models',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ChatCompletionsRoute = V1ChatCompletionsRouteImport.update({
  id: '/v1/chat/completions',
  path: '/v1/chat/completions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connections': typeof ConnectionsRoute
  '/models': typeof ModelsRoute
  '/resources': typeof ResourcesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/v1/models': typeof V1ModelsRoute
  '/v1/chat/completions': typeof V1ChatCompletionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/connections': typeof ConnectionsRoute
  '/models': typeof ModelsRoute
  '/resources': typeof ResourcesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/v1/models': typeof V1ModelsRoute
  '/v1/chat/completions': typeof V1ChatCompletionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/connections': typeof ConnectionsRoute
  '/models': typeof ModelsRoute
  '/resources': typeof ResourcesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/v1/models': typeof V1ModelsRoute
  '/v1/chat/completions': typeof V1ChatCompletionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/connections'
    | '/models'
    | '/resources'
    | '/dashboard'
    | '/v1/models'
    | '/v1/chat/completions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/connections'
    | '/models'
    | '/resources'
    | '/dashboard'
    | '/v1/models'
    | '/v1/chat/completions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/connections'
    | '/models'
    | '/resources'
    | '/_authenticated/dashboard'
    | '/v1/models'
    | '/v1/chat/completions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConnectionsRoute: typeof ConnectionsRoute
  ModelsRoute: typeof ModelsRoute
  ResourcesRoute: typeof ResourcesRoute
  V1ModelsRoute: typeof V1ModelsRoute
  V1ChatCompletionsRoute: typeof V1ChatCompletionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/v1/models': {
      id: '/v1/models'
      path: '/v1/models'
      fullPath: '/v1/models'
      preLoaderRoute: typeof V1ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/chat/completions': {
      id: '/v1/chat/completions'
      path: '/v1/chat/completions'
      fullPath: '/v1/chat/completions'
      preLoaderRoute: typeof V1ChatCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConnectionsRoute: ConnectionsRoute,
  ModelsRoute: ModelsRoute,
  ResourcesRoute: ResourcesRoute,
  V1ModelsRoute: V1ModelsRoute,
  V1ChatCompletionsRoute: V1ChatCompletionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
