-- Audited third-party resources are visible metadata only. None are executable or installable.
insert into public.resources (
  slug, name, description, resource_type, category_slug, author, source,
  version, license, installation_type, installation_config, supported_clients,
  verified, featured, published
) values
('open-skill-vetter','Skill Vetter','Promising pre-ingestion review policy; security review required.','skill','developer','ClawHub','curated-registry','metadata','MIT-0','metadata','{"canonical_url":"https://clawhub.ai/spclaudehome/skills/skill-vetter","review_state":"review_required","risk":"medium","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-qmd','Qmd','Knowledge indexing requires privacy and filesystem review.','mcp','knowledge','ClawHub','curated-registry','metadata','MIT-0','metadata','{"canonical_url":"https://clawhub.ai/steipete/skills/qmd","review_state":"review_required","risk":"high","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-planning-with-files','Planning with Files','Hooks may inject local content into model context.','skill','developer','ClawHub','curated-registry','metadata','MIT-0','metadata','{"canonical_url":"https://clawhub.ai/othmanadi/skills/planning-with-files","review_state":"review_required","risk":"high","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-superpowers-dev-workflow','Superpowers Dev Workflow','Executes commands and spawns agents.','skill','developer','ClawHub','curated-registry','metadata','MIT-0','metadata','{"canonical_url":"https://clawhub.ai/wlshlad85/skills/superpowers","review_state":"review_required","risk":"high","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-terminal','Open Terminal','Remote shell requires isolation and explicit approval.','tool','developer','Open WebUI','curated-registry','metadata','MIT','metadata','{"canonical_url":"https://github.com/open-webui/open-terminal","review_state":"review_required","risk":"critical","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-mcpo','mcpo','Duplicates the existing Open-Connect MCP/OpenAPI gateway.','mcp','developer','Open WebUI','curated-registry','metadata','MIT','metadata','{"canonical_url":"https://github.com/open-webui/mcpo","review_state":"rejected","risk":"high","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-swarmclaw','SwarmClaw','Research adapter only; overlaps Open-System orchestration.','agent','developer','SwarmClaw','curated-registry','metadata','MIT','metadata','{"canonical_url":"https://www.swarmclaw.ai/","review_state":"review_required","risk":"high","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-fs-safe','OpenClaw fs-safe','Native bindings and filesystem boundaries require security review.','tool','security','OpenClaw','curated-registry','metadata','MIT','metadata','{"canonical_url":"https://github.com/openclaw/fs-safe","review_state":"review_required","risk":"high","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-rocketchat-plugin','Rocket.Chat OpenClaw Plugin','Requires admin access, bot creation, and credential configuration.','plugin','connections','Rocket.Chat','curated-registry','metadata','MIT','metadata','{"canonical_url":"https://github.com/RocketChat/OpenClaw.Plugin","review_state":"review_required","risk":"high","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-learn-skills','learn-skills.dev','No detected license; metadata only.','skill','developer','NeverSight','curated-registry','metadata',null,'metadata','{"canonical_url":"https://github.com/NeverSight/learn-skills.dev","review_state":"review_required","risk":"high","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-awesome-openclaw-use-cases-cn','Awesome OpenClaw Use Cases CN','License terms and untrusted prompt content require review.','guide','knowledge','AIPMAndy','curated-registry','metadata','Apache-2.0 with additional terms','metadata','{"canonical_url":"https://github.com/AIPMAndy/awesome-openclaw-use-cases-cn","review_state":"review_required","risk":"medium","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-acpx','OpenClaw acpx','Controls persistent agent sessions, permissions, and tool events.','plugin','developer','OpenClaw','curated-registry','metadata','MIT','metadata','{"canonical_url":"https://github.com/openclaw/acpx","review_state":"review_required","risk":"high","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-deja-vu','deja-vu','Cross-agent history injection creates privacy and contamination risk.','tool','knowledge','vshulcz','curated-registry','metadata','MIT','metadata','{"canonical_url":"https://github.com/vshulcz/deja-vu","review_state":"review_required","risk":"critical","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-langbot','LangBot','Substantial overlap with Open-Hub and Open-System.','agent','developer','LangBot','curated-registry','metadata','Apache-2.0','metadata','{"canonical_url":"https://github.com/langbot-app/LangBot","review_state":"rejected","risk":"high","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-lobe-bench-skill','Lobe Bench Skill','No detected license or sufficient package description.','skill','developer','LobeHub','curated-registry','metadata',null,'metadata','{"canonical_url":"https://github.com/lobehub/lobe-bench-skill","review_state":"review_required","risk":"unknown","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-clownfish','OpenClaw Clownfish','Can close or merge GitHub work; repository governance approval required.','agent','developer','OpenClaw','curated-registry','metadata','MIT','metadata','{"canonical_url":"https://github.com/openclaw/clownfish","review_state":"review_required","risk":"critical","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-agent-session-query','agent-session-query','Session-history access requires privacy and retention review.','mcp','knowledge','itswl','curated-registry','metadata','MIT','metadata','{"canonical_url":"https://github.com/itswl/agent-session-query","review_state":"review_required","risk":"high","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-crabbox','OpenClaw Crabbox','Executes commands across containers, SSH hosts, and cloud machines.','tool','developer','OpenClaw','curated-registry','metadata','MIT','metadata','{"canonical_url":"https://github.com/openclaw/crabbox","review_state":"review_required","risk":"critical","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-tale','Tale','Duplicates Open-System orchestration with weaker provenance.','agent','developer','Tale Project','curated-registry','metadata',null,'metadata','{"canonical_url":"https://github.com/tale-project/tale","review_state":"rejected","risk":"high","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-microsandbox-reef','microsandbox-reef','Beta microVM runtime; authentication and host-secret boundaries require review.','tool','security','SKALE Labs','curated-registry','metadata','MIT','metadata','{"canonical_url":"https://github.com/skalenetwork/microsandbox-reef","review_state":"review_required","risk":"critical","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-casdoor','Casdoor','Identity reference only; overlaps Supabase authentication and the broker.','app','connections','Casdoor','curated-registry','metadata','Apache-2.0','metadata','{"canonical_url":"https://github.com/casdoor/casdoor","review_state":"rejected","risk":"high","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-openclaw-cve-tracker','OpenClaw CVE Tracker','Useful advisory metadata but must be reconciled with authoritative CVE sources.','guide','security','jgamblin','curated-registry','metadata','MIT','metadata','{"canonical_url":"https://github.com/jgamblin/OpenClawCVEs","review_state":"review_required","risk":"medium","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-lossless-claw','Lossless Claw','Full transcript persistence and recall require privacy controls.','tool','knowledge','Martian Engineering','curated-registry','metadata','MIT','metadata','{"canonical_url":"https://github.com/Martian-Engineering/lossless-claw","review_state":"review_required","risk":"critical","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-nemoclaw','NVIDIA NemoClaw','Alpha sandbox runtime; privilege, egress, and escape boundaries require testing.','tool','security','NVIDIA','curated-registry','metadata','Apache-2.0','metadata','{"canonical_url":"https://github.com/NVIDIA/NemoClaw","review_state":"review_required","risk":"critical","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-aris','ARIS','Runs experiments, shell commands, plugins, skills, and persistent knowledge.','skill','developer','wanshuiyin','curated-registry','metadata','MIT','metadata','{"canonical_url":"https://github.com/wanshuiyin/Auto-claude-code-research-in-sleep","review_state":"review_required","risk":"critical","executable":false}'::jsonb,array['Open-Connect'],false,false,true),
('open-u-claw','U-Claw','Portable runtime duplicates existing capabilities and carries sensitive state.','app','developer','InternLM','curated-registry','metadata',null,'metadata','{"canonical_url":"https://github.com/InternLM/U-Claw","review_state":"rejected","risk":"high","executable":false}'::jsonb,array['Open-Connect'],false,false,true)
on conflict (slug) do update set
  name=excluded.name, description=excluded.description, resource_type=excluded.resource_type,
  category_slug=excluded.category_slug, author=excluded.author, source=excluded.source,
  version=excluded.version, license=excluded.license, installation_type=excluded.installation_type,
  installation_config=excluded.installation_config, supported_clients=excluded.supported_clients,
  verified=false, featured=false, published=true, updated_at=now();
