-- Publish the provider kits without embedding credentials.
insert into public.resources (slug, name, description, resource_type, category_slug, author, source, source_url, version, license, installation_type, installation_config, supported_clients, verified, featured, published)
values ('open-github-kit', 'Open GitHub Kit', 'GitHub repository, Actions, release, package, and deployment operations.', 'plugin', 'developer', 'HillStreet Information Technology Services', 'first-party', 'https://open-connect.site/downloads/open-github-kit.zip', '1.0.0', 'proprietary', 'package', '{"package_url":"https://open-connect.site/downloads/open-github-kit.zip","mcp_url":"https://open-connect.site/mcp","credential_transport":"opaque_reference_only","default_access":"provider_authorized_read_write","production_approval_required":true,"destructive_approval_required":true}'::jsonb, array['ChatGPT','Codex','Open-Connect'], true, false, true)
on conflict (slug) do update set name=excluded.name, description=excluded.description, resource_type=excluded.resource_type, category_slug=excluded.category_slug, author=excluded.author, source=excluded.source, source_url=excluded.source_url, version=excluded.version, license=excluded.license, installation_type=excluded.installation_type, installation_config=excluded.installation_config, supported_clients=excluded.supported_clients, verified=excluded.verified, featured=excluded.featured, published=excluded.published, updated_at=now();

insert into public.resources (slug, name, description, resource_type, category_slug, author, source, source_url, version, license, installation_type, installation_config, supported_clients, verified, featured, published)
values ('open-dockerhub-kit', 'Open Docker Hub Kit', 'Docker Hub image publishing, scanning, provenance, and delivery operations.', 'plugin', 'developer', 'HillStreet Information Technology Services', 'first-party', 'https://open-connect.site/downloads/open-dockerhub-kit.zip', '1.0.0', 'proprietary', 'package', '{"package_url":"https://open-connect.site/downloads/open-dockerhub-kit.zip","mcp_url":"https://open-connect.site/mcp","credential_transport":"opaque_reference_only","default_access":"provider_authorized_read_write","production_approval_required":true,"destructive_approval_required":true}'::jsonb, array['ChatGPT','Codex','Open-Connect'], true, false, true)
on conflict (slug) do update set name=excluded.name, description=excluded.description, resource_type=excluded.resource_type, category_slug=excluded.category_slug, author=excluded.author, source=excluded.source, source_url=excluded.source_url, version=excluded.version, license=excluded.license, installation_type=excluded.installation_type, installation_config=excluded.installation_config, supported_clients=excluded.supported_clients, verified=excluded.verified, featured=excluded.featured, published=excluded.published, updated_at=now();

insert into public.resources (slug, name, description, resource_type, category_slug, author, source, source_url, version, license, installation_type, installation_config, supported_clients, verified, featured, published)
values ('open-cloudflare-kit', 'Open Cloudflare Kit', 'Cloudflare edge, DNS, Workers, storage, security, and observability operations.', 'plugin', 'developer', 'HillStreet Information Technology Services', 'first-party', 'https://open-connect.site/downloads/open-cloudflare-kit.zip', '1.0.0', 'proprietary', 'package', '{"package_url":"https://open-connect.site/downloads/open-cloudflare-kit.zip","mcp_url":"https://open-connect.site/mcp","credential_transport":"opaque_reference_only","default_access":"provider_authorized_read_write","production_approval_required":true,"destructive_approval_required":true}'::jsonb, array['ChatGPT','Codex','Open-Connect'], true, false, true)
on conflict (slug) do update set name=excluded.name, description=excluded.description, resource_type=excluded.resource_type, category_slug=excluded.category_slug, author=excluded.author, source=excluded.source, source_url=excluded.source_url, version=excluded.version, license=excluded.license, installation_type=excluded.installation_type, installation_config=excluded.installation_config, supported_clients=excluded.supported_clients, verified=excluded.verified, featured=excluded.featured, published=excluded.published, updated_at=now();

insert into public.resources (slug, name, description, resource_type, category_slug, author, source, source_url, version, license, installation_type, installation_config, supported_clients, verified, featured, published)
values ('open-supabase-kit', 'Open Supabase Kit', 'Supabase database, Auth, Storage, Realtime, and Edge Function operations.', 'plugin', 'developer', 'HillStreet Information Technology Services', 'first-party', 'https://open-connect.site/downloads/open-supabase-kit.zip', '1.0.0', 'proprietary', 'package', '{"package_url":"https://open-connect.site/downloads/open-supabase-kit.zip","mcp_url":"https://open-connect.site/mcp","credential_transport":"opaque_reference_only","default_access":"provider_authorized_read_write","production_approval_required":true,"destructive_approval_required":true}'::jsonb, array['ChatGPT','Codex','Open-Connect'], true, false, true)
on conflict (slug) do update set name=excluded.name, description=excluded.description, resource_type=excluded.resource_type, category_slug=excluded.category_slug, author=excluded.author, source=excluded.source, source_url=excluded.source_url, version=excluded.version, license=excluded.license, installation_type=excluded.installation_type, installation_config=excluded.installation_config, supported_clients=excluded.supported_clients, verified=excluded.verified, featured=excluded.featured, published=excluded.published, updated_at=now();

insert into public.resources (slug, name, description, resource_type, category_slug, author, source, source_url, version, license, installation_type, installation_config, supported_clients, verified, featured, published)
values ('open-sentry-kit', 'Open Sentry Kit', 'Sentry errors, releases, tracing, performance, alerts, and source map operations.', 'plugin', 'developer', 'HillStreet Information Technology Services', 'first-party', 'https://open-connect.site/downloads/open-sentry-kit.zip', '1.0.0', 'proprietary', 'package', '{"package_url":"https://open-connect.site/downloads/open-sentry-kit.zip","mcp_url":"https://open-connect.site/mcp","credential_transport":"opaque_reference_only","default_access":"provider_authorized_read_write","production_approval_required":true,"destructive_approval_required":true}'::jsonb, array['ChatGPT','Codex','Open-Connect'], true, false, true)
on conflict (slug) do update set name=excluded.name, description=excluded.description, resource_type=excluded.resource_type, category_slug=excluded.category_slug, author=excluded.author, source=excluded.source, source_url=excluded.source_url, version=excluded.version, license=excluded.license, installation_type=excluded.installation_type, installation_config=excluded.installation_config, supported_clients=excluded.supported_clients, verified=excluded.verified, featured=excluded.featured, published=excluded.published, updated_at=now();

insert into public.resources (slug, name, description, resource_type, category_slug, author, source, source_url, version, license, installation_type, installation_config, supported_clients, verified, featured, published)
values ('open-zeabur-kit', 'Open Zeabur Kit', 'Zeabur service deployment, domains, variables, health, logs, and rollback operations.', 'plugin', 'developer', 'HillStreet Information Technology Services', 'first-party', 'https://open-connect.site/downloads/open-zeabur-kit.zip', '1.0.0', 'proprietary', 'package', '{"package_url":"https://open-connect.site/downloads/open-zeabur-kit.zip","mcp_url":"https://open-connect.site/mcp","credential_transport":"opaque_reference_only","default_access":"provider_authorized_read_write","production_approval_required":true,"destructive_approval_required":true}'::jsonb, array['ChatGPT','Codex','Open-Connect'], true, false, true)
on conflict (slug) do update set name=excluded.name, description=excluded.description, resource_type=excluded.resource_type, category_slug=excluded.category_slug, author=excluded.author, source=excluded.source, source_url=excluded.source_url, version=excluded.version, license=excluded.license, installation_type=excluded.installation_type, installation_config=excluded.installation_config, supported_clients=excluded.supported_clients, verified=excluded.verified, featured=excluded.featured, published=excluded.published, updated_at=now();

insert into public.resources (slug, name, description, resource_type, category_slug, author, source, source_url, version, license, installation_type, installation_config, supported_clients, verified, featured, published)
values ('open-databricks-kit', 'Open Databricks Kit', 'Databricks governed data, analytics, jobs, pipelines, compute, and AI operations.', 'plugin', 'developer', 'HillStreet Information Technology Services', 'first-party', 'https://open-connect.site/downloads/open-databricks-kit.zip', '1.0.0', 'proprietary', 'package', '{"package_url":"https://open-connect.site/downloads/open-databricks-kit.zip","mcp_url":"https://open-connect.site/mcp","credential_transport":"opaque_reference_only","default_access":"provider_authorized_read_write","production_approval_required":true,"destructive_approval_required":true}'::jsonb, array['ChatGPT','Codex','Open-Connect'], true, false, true)
on conflict (slug) do update set name=excluded.name, description=excluded.description, resource_type=excluded.resource_type, category_slug=excluded.category_slug, author=excluded.author, source=excluded.source, source_url=excluded.source_url, version=excluded.version, license=excluded.license, installation_type=excluded.installation_type, installation_config=excluded.installation_config, supported_clients=excluded.supported_clients, verified=excluded.verified, featured=excluded.featured, published=excluded.published, updated_at=now();

insert into public.resources (slug, name, description, resource_type, category_slug, author, source, source_url, version, license, installation_type, installation_config, supported_clients, verified, featured, published)
values ('open-devapps-kit', 'Open DevApps Kit', 'One coordinated delivery toolkit for GitHub, Docker Hub, Cloudflare, Supabase, Sentry, Zeabur, and Databricks.', 'plugin', 'developer', 'HillStreet Information Technology Services', 'first-party', 'https://open-connect.site/downloads/open-devapps-kit.zip', '1.0.0', 'proprietary', 'package', '{"package_url":"https://open-connect.site/downloads/open-devapps-kit.zip","mcp_url":"https://open-connect.site/mcp","credential_transport":"opaque_reference_only","default_access":"provider_authorized_read_write","production_approval_required":true,"destructive_approval_required":true}'::jsonb, array['ChatGPT','Codex','Open-Connect'], true, true, true)
on conflict (slug) do update set name=excluded.name, description=excluded.description, resource_type=excluded.resource_type, category_slug=excluded.category_slug, author=excluded.author, source=excluded.source, source_url=excluded.source_url, version=excluded.version, license=excluded.license, installation_type=excluded.installation_type, installation_config=excluded.installation_config, supported_clients=excluded.supported_clients, verified=excluded.verified, featured=excluded.featured, published=excluded.published, updated_at=now();
