-- HillStreet E2E skills + browser skills → public.resources (idempotent by slug)
-- Apply when Supabase is reachable. Source packages: hillstreet-ph/open-custom-skills
-- Binary packages should be uploaded to Storage bucket resource-packages separately.

INSERT INTO public.resources (
  slug, name, description, resource_type, category_slug, author, source,
  source_url, verified, featured, published, version, supported_clients
) VALUES
  ('inspect-analyze-e2e', 'Inspect Analyze E2E',
   'Pre-change inspection, architecture discovery, gap analysis for Open Connect.',
   'skill', 'developer', 'HillStreet', 'open-custom-skills',
   'https://github.com/hillstreet-ph/open-custom-skills', true, true, true, '1.0.0',
   ARRAY['claude','cursor','openai','grok']),
  ('github-e2e-setup', 'GitHub E2E Setup',
   'Production GitHub setup: branches, rulesets, Actions, environments, releases.',
   'skill', 'developer', 'HillStreet', 'open-custom-skills',
   'https://github.com/hillstreet-ph/open-custom-skills', true, true, true, '1.0.0',
   ARRAY['claude','cursor','openai','grok']),
  ('cloudflare-e2e-setup', 'Cloudflare E2E Setup',
   'Cloudflare Pages, DNS, TLS, KV, Workers lifecycle for open-connect.site.',
   'skill', 'developer', 'HillStreet', 'open-custom-skills',
   'https://github.com/hillstreet-ph/open-custom-skills', true, true, true, '1.0.0',
   ARRAY['claude','cursor','openai','grok']),
  ('supabase-e2e-setup', 'Supabase E2E Setup',
   'Supabase Auth, RLS, migrations, Storage, Edge Functions for Open Connect.',
   'skill', 'developer', 'HillStreet', 'open-custom-skills',
   'https://github.com/hillstreet-ph/open-custom-skills', true, true, true, '1.0.0',
   ARRAY['claude','cursor','openai','grok']),
  ('credentials-e2e-setup', 'Credentials E2E Setup',
   'Secrets, env vars, OAuth, vault references — never raw secrets to clients.',
   'skill', 'security', 'HillStreet', 'open-custom-skills',
   'https://github.com/hillstreet-ph/open-custom-skills', true, true, true, '1.0.0',
   ARRAY['claude','cursor','openai','grok']),
  ('complete-e2e-prompt', 'Complete E2E Prompt',
   'Universal production E2E orchestrator prompt for GH + CF + SB stack.',
   'skill', 'ai', 'HillStreet', 'open-custom-skills',
   'https://github.com/hillstreet-ph/open-custom-skills', true, true, true, '1.0.0',
   ARRAY['claude','cursor','openai','grok']),
  ('gh-cf-sb-setup', 'GitHub Cloudflare Supabase Setup',
   'Orchestrator skill for GH + CF + SB only (no Vercel).',
   'skill', 'developer', 'HillStreet', 'open-custom-skills',
   'https://github.com/hillstreet-ph/open-custom-skills', true, true, true, '1.0.0',
   ARRAY['claude','cursor','openai','grok']),
  ('docker-e2e-setup', 'Docker E2E Setup',
   'Docker and Docker Hub lifecycle for optional worker images.',
   'skill', 'developer', 'HillStreet', 'open-custom-skills',
   'https://github.com/hillstreet-ph/open-custom-skills', true, false, true, '1.0.0',
   ARRAY['claude','cursor','openai','grok']),
  ('railway-e2e-setup', 'Railway E2E Setup',
   'Optional Railway runtime — preview/fallback only, not OC public edge.',
   'skill', 'developer', 'HillStreet', 'open-custom-skills',
   'https://github.com/hillstreet-ph/open-custom-skills', true, false, true, '1.0.0',
   ARRAY['claude','cursor','openai','grok']),
  ('zeabur-e2e-setup', 'Zeabur E2E Setup',
   'Optional Zeabur workers — not the public edge for open-connect.site.',
   'skill', 'developer', 'HillStreet', 'open-custom-skills',
   'https://github.com/hillstreet-ph/open-custom-skills', true, false, true, '1.0.0',
   ARRAY['claude','cursor','openai','grok']),
  ('gh-cf-sb-zb-setup', 'GH CF SB Zeabur Setup',
   'Stack orchestrator including optional Zeabur.',
   'skill', 'developer', 'HillStreet', 'open-custom-skills',
   'https://github.com/hillstreet-ph/open-custom-skills', true, false, true, '1.0.0',
   ARRAY['claude','cursor','openai','grok']),
  ('gh-dh-cf-sb-zb-setup', 'Full Stack GH DH CF SB ZB',
   'Full orchestrator with Docker Hub + Zeabur optional paths.',
   'skill', 'developer', 'HillStreet', 'open-custom-skills',
   'https://github.com/hillstreet-ph/open-custom-skills', true, false, true, '1.0.0',
   ARRAY['claude','cursor','openai','grok']),
  ('agent-browser', 'Agent Browser',
   'Browser automation skill package for agent-driven browsing.',
   'skill', 'ai', 'HillStreet', 'open-connect',
   'https://open-connect.site/downloads/skills/agent-browser/', true, true, true, '1.0.0',
   ARRAY['claude','cursor','openai','grok']),
  ('cloudflare-browser', 'Cloudflare Browser',
   'Cloudflare-oriented browser skill package.',
   'skill', 'ai', 'HillStreet', 'open-connect',
   'https://open-connect.site/downloads/skills/cloudflare-browser/', true, true, true, '1.0.0',
   ARRAY['claude','cursor','openai','grok']),
  ('multion-autonomous', 'MultiOn Autonomous',
   'Autonomous browser control skill (MultiOn-oriented).',
   'skill', 'ai', 'HillStreet', 'open-connect',
   'https://open-connect.site/downloads/skills/multion-autonomous/', true, true, true, '1.0.0',
   ARRAY['claude','cursor','openai','grok']),
  ('complete-prompts-library', 'Complete Prompts Library',
   'Development prompts library (PDF) from open-custom-skills.',
   'prompt', 'ai', 'HillStreet', 'open-custom-skills',
   'https://github.com/hillstreet-ph/open-custom-skills', true, false, true, '1.0.0',
   ARRAY['claude','cursor','openai','grok'])
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  resource_type = EXCLUDED.resource_type,
  category_slug = EXCLUDED.category_slug,
  source = EXCLUDED.source,
  source_url = EXCLUDED.source_url,
  verified = EXCLUDED.verified,
  featured = EXCLUDED.featured,
  published = EXCLUDED.published,
  version = EXCLUDED.version,
  supported_clients = EXCLUDED.supported_clients,
  updated_at = now();
